### PR TITLE
fix: avoid overflow on 32 bit architectures

### PR DESCRIPTION
**Pull request by ncitron**
addresses #27

### CODE REVIEW

**Comment by claravanstaden** [comment]
I also addressed this in https://github.com/ralexstokes/ssz-rs/pull/25/files#diff-97dff6cb7d3f1bea2c98e61d85eeaab0dfc941e86dbc3679aa69a51d528c8801R6. 😃 We can probably merge this one first @ralexstokes, nice and small.

**Review by ralexstokes — APPROVED** [review]
this works for me!

I don't really see why but if there is ever any reason why we want to optimize out the extra 4 bytes of overhead we can just hardcode the limit directly

also it looks like there are several clippy lints added in the latest rust version that is failing the build -- I can fix them and then we can rebase this on top of that

**Comment by ralexstokes** [comment]
@ncitron if you rebase from `main` this should unblock the CI

**Comment by ncitron** [comment]
Rebased

**Pull request merged**
